version: '3.7'

services:
  # db:
  #   container_name: 'db'
  #   image: mysql:5.7
  #   ports:
  #     - '3307:3306'
  #   environment:
  #      MYSQL_DATABASE: 'appdb'
  #      MYSQL_PASSWORD: 'Yusuf@2021'
  #      MYSQL_ROOT_PASSWORD: 'Yusuf@2021'
  #   volumes:
  #     - 'db:/var/lib/mysql'
  #   # command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  #   command: GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION

  # memcached:
  #   container_name: 'memcached'
  #   image: 'memcached:latest'
  #   ports:
  #     - "11212:11211"

  gecss_v3egine:
    restart: always
    image: gecss_v3egine
    container_name: "gecss_v3egine"
    env_file:
      - .env
    build:
      context: .
    volumes:
      - static:/static
      - '.:/base_directory'
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached

volumes:
  static:
  .: