# Generated by Django 4.0.8 on 2022-11-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentpayment',
            old_name='tomDate',
            new_name='toDate',
        ),
    ]
