# Generated by Django 4.0.5 on 2022-06-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bikes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
