# Generated by Django 4.0.5 on 2022-06-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_useraccount_bikes_alter_useraccount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('Daily Deposit', 'Daily Deposit'), ('Swap Battery', 'Swap Battery')], default='Daily Deposit', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Flag', 'Flag')], default='Paid', max_length=20),
        ),
    ]
