# Generated by Django 4.0.8 on 2022-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_purpose_alter_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=555)),
                ('quantity', models.CharField(default=1, max_length=18)),
                ('units_conversion', models.CharField(blank=True, default='None', max_length=50)),
                ('price', models.CharField(default=1, max_length=12)),
                ('approvedby', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=155)),
                ('date', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
