# Generated by Django 4.0.8 on 2022-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='department',
            field=models.CharField(default='Office', max_length=255),
        ),
    ]
