# Generated by Django 4.0.8 on 2022-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expense_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
