# Generated by Django 4.0.5 on 2022-09-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_mpesacipher_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacipher',
            name='status',
            field=models.CharField(default='Paid', max_length=20),
        ),
    ]
