# Generated by Django 4.0.5 on 2022-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_mpesacipher_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(max_length=50)),
                ('transID', models.CharField(max_length=50)),
                ('transTime', models.CharField(max_length=50)),
                ('transAmount', models.CharField(max_length=50)),
                ('billRefNumber', models.CharField(max_length=50)),
                ('orgAccountBalance', models.CharField(max_length=50)),
                ('MSISDN', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
            ],
        ),
    ]
