# Generated by Django 4.1.3 on 2022-11-15 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0004_mpesapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 13, 47, 33, 255132, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='transAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
