# Generated by Django 4.1.3 on 2022-11-15 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0005_mpesapayment_created_alter_mpesapayment_transamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(max_length=50)),
                ('transID', models.CharField(max_length=50)),
                ('transTime', models.CharField(max_length=50)),
                ('transAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('billRefNumber', models.CharField(max_length=50)),
                ('orgAccountBalance', models.CharField(max_length=50)),
                ('MSISDN', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 19, 43, 884877)),
        ),
    ]
