# Generated by Django 4.0.5 on 2022-07-06 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNo', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('alt_phone', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('operation_area', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
