# Generated by Django 4.0.5 on 2022-06-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
    ]
