# Generated by Django 4.0.5 on 2022-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_batterystation'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterystation',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='batterystation',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
