# Generated by Django 4.0.5 on 2022-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0004_batteryswap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryswap',
            name='battery_code2',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
