# Generated by Django 4.0.5 on 2022-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0006_remove_batteryswap_battery_code2_batteryswap_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryswap',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
