# Generated by Django 4.0.5 on 2022-06-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=555)),
                ('image', models.ImageField(upload_to='battery_centers')),
                ('charged_battery', models.PositiveIntegerField(default=0)),
                ('discharged_battery', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
