# Generated by Django 4.0.5 on 2022-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gecssbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecssbranch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Dormant', 'Dormant'), ('Ongoing', 'Ongoing'), ('Construction', 'Construction')], default='Active', max_length=50),
        ),
    ]
