# Generated by Django 4.0.5 on 2022-07-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_gecssbranch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gecssbranch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Dormant', 'Dormant'), ('Agent', 'Agent'), ('Ongoing', 'Ongoing'), ('Construction', 'Construction')], default='Active', max_length=50),
        ),
    ]
