# Generated by Django 4.0.8 on 2022-11-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_gecssbranch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=555)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='batterystation',
            name='image',
        ),
    ]
