# Generated by Django 4.0.5 on 2022-06-24 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motobikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplate', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Leased', 'Leased'), ('Sold', 'Sold'), ('Gecss', 'Gecss')], default='Gecss', max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Retrofitted', 'Retrofitted')], default='New', max_length=20)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
